services:
  - type: web
    name: nuxt3-app
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm preview
    envVars:
      - key: NODE_VERSION
        value: 20
